- id: '1690008367348'
  alias: Bathroom Lamp Light Button
  description: ''
  trigger:
  - device_id: a22e589da09cbccb89a6e82b89711633
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 861be6962ec8cbcd256fc8ebcf1f6b51
    entity_id: e0b4baf7dfa54a54c1b25fbcb0e4d65c
    domain: switch
  mode: single
- id: '1690008412276'
  alias: Living Room Front Light Button
  description: ''
  trigger:
  - device_id: 337e5c5ca4b651488d5bf33c368cebaf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 763bc7b57828667de8165dc2ca65f776
    entity_id: 69181f2e1d1d19e465147287adb6824b
    domain: switch
  mode: single
- id: '1690008450276'
  alias: Bedroom Light Button
  description: ''
  trigger:
  - device_id: 27b7195188337d0ccf48e1477d71cb65
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 861be6962ec8cbcd256fc8ebcf1f6b51
    entity_id: e0b4baf7dfa54a54c1b25fbcb0e4d65c
    domain: switch
  mode: single
- id: '1690008585480'
  alias: Dog Gate Timer
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 306f507b5f864d595458ae58ab5b4f23
    entity_id: 936b0e57c584f15d223942956a862682
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: time
    after: 09:00:00
    before: '21:00:00'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.all_speakers
    data:
      media_content_id: media-source://tts/tts.google_en_com?message=The+dog+gate+is+open.&language=en-us
      media_content_type: provider
    metadata:
      title: The dog gate is open.
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/tts.google_en_com?message=The+dog+gate+is+open.&language=en-us
  mode: single
