# Loads default set of integrations. Do not remove.
default_config:

bluetooth:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate:
  - platform: generic_thermostat
    name: Thermostat
    heater: switch.ac_plug
    target_sensor: sensor.lumi_lumi_weather_temperature
    min_temp: 75
    max_temp: 81
    ac_mode: true
    target_temp: 78
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "cool"
    away_temp: 16
    precision: 0.1